const courseList = [
    'ABI - Engenharia',
    'Administração',
    'Arqueologia',
    'Arquitetura e Urbanismo',
    'Artes Visuais',
    'Biblioteconomia',
    'Biomedicina',
    'Cinema e Audiovisual',
    'Ciência Política',
    'Ciência da Computação',
    'Ciência de Materiais',
    'Ciências Ambientais',
    'Ciências Atuariais',
    'Ciências Biológicas',
    'Ciências Contábeis',
    'Ciências Econômicas',
    'Ciências Sociais',
    'Comunicação Social',
    'Dança',
    'Design',
    'Direito',
    'Educação Escolar Quilombola',
    'Educação Física',
    'Enfermagem',
    'Engenharia Biomédica',
    'Engenharia Cartográfica e de Agrimensura',
    'Engenharia Civil',
    'Engenharia Eletrônica',
    'Engenharia Elétrica',
    'Engenharia Mecânica',
    'Engenharia Naval',
    'Engenharia Química',
    'Engenharia da Computação',
    'Engenharia de Alimentos',
    'Engenharia de Controle e Automação',
    'Engenharia de Energia',
    'Engenharia de Materiais',
    'Engenharia de Minas',
    'Engenharia de Produção',
    'Engenharia de Telecomunicações',
    'Estatística',
    'Estudos de Mídia',
    'Expressão Gráfica',
    'Farmácia',
    'Filosofia',
    'Fisioterapia',
    'Fonoaudiologia',
    'Física',
    'Geografia',
    'Geologia',
    'Gestão da Informação',
    'História',
    'Hotelaria',
    'Inteligência Artificial',
    'Intercultural Indígena',
    'Interdisciplinar em Ciência e Tecnologia',
    'Jornalismo',
    'Letras',
    'Letras Espanhol',
    'Letras Francês',
    'Letras Inglês',
    'Letras Libras',
    'Letras Português',
    'Letras-Língua Espanhola',
    'Letras-Língua Portuguesa',
    'Matemática',
    'Matemática Aplicada',
    'Medicina',
    'Museologia',
    'Música',
    'Música - Canto',
    'Música - Instrumento',
    'Nutrição',
    'Oceanografia',
    'Odontologia',
    'Pedagogia',
    'Psicologia',
    'Publicidade e Propaganda',
    'Química',
    'Química Industrial',
    'Rádio, TV e Internet',
    'Saúde Coletiva',
    'Secretariado Executivo',
    'Serviço Social',
    'Sistemas de Informação',
    'Teatro',
    'Terapia Ocupacional',
    'Turismo'
];

const centerList = [
    'CAA',
    'CAC',
    'CB',
    'CCEN',
    'CCJ',
    'CCM',
    'CCS',
    'CCSA',
    'CE',
    'CFCH',
    'CIN',
    'CAV',
    'CTG'
];

export { courseList, centerList };